-- 17.04
-- Rifle
AddCustomShipment("AK-47", "models/weapons/w_rif_ak47.mdl", "ptp_cs_ak47", 43000, 5, false, 0, false, {TEAM_GUN}) -- weapon_crossbow
AddCustomShipment("P228", "models/weapons/w_pist_p228.mdl", "ptp_cs_p228", 9000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("P90", "models/weapons/w_smg_p90.mdl", "ptp_cs_p90", 20000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("TMP", "models/weapons/w_smg_tmp.mdl", "ptp_cs_tmp", 23000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Galil", "models/weapons/w_rif_galil.mdl", "ptp_cs_galil", 35500, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Five-Seven", "models/weapons/w_pist_fiveseven.mdl", "ptp_cs_fiveseven", 6500, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("MP5", "models/weapons/w_smg_mp5.mdl", "ptp_cs_mp5", 15500, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("MAC10", "models/weapons/w_smg_mac10.mdl", "ptp_cs_mac10", 13000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Glock", "models/weapons/w_pist_glock18.mdl", "ptp_cs_glock", 4500, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("SG550", "models/weapons/w_snip_sg550.mdl", "ptp_cs_sg550", 40000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("AWP", "models/weapons/w_snip_awp.mdl", "ptp_cs_awp", 66000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Scout", "models/weapons/w_snip_scout.mdl", "ptp_cs_scout", 35000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("SG552", "models/weapons/w_rif_sg552.mdl", "ptp_cs_sg552", 55000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Knife", "models/weapons/w_knife_t.mdl", "csgo_bayonet", 1000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("M249", "models/weapons/w_mach_m249para.mdl", "ptp_cs_para", 75000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Leone Super", "models/weapons/w_shot_m3super90.mdl", "ptp_cs_pumpshotgun", 26000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Leone Auto", "models/weapons/w_shot_xm1014.mdl", "ptp_cs_autoshotgun", 28000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Dual Elites", "models/weapons/w_pist_elite.mdl", "ptp_cs_elites", 9500, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("AUG", "models/weapons/w_rif_aug.mdl", "ptp_cs_aug", 45000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Famas", "models/weapons/w_rif_famas.mdl", "ptp_cs_famas", 26000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("G3SG1", "models/weapons/w_snip_g3sg1.mdl", "ptp_cs_g3sg1", 55000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("UMP45", "models/weapons/w_smg_ump45.mdl", "ptp_cs_ump45", 18000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("M4A1", "models/weapons/w_rif_m4a1.mdl", "ptp_cs_m4", 35000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("Deagle", "models/weapons/w_pist_deagle.mdl", "ptp_cs_deagle", 10000, 5, false, 0, false, {TEAM_GUN})
AddCustomShipment("USP", "models/weapons/w_pist_usp.mdl", "ptp_cs_usp", 5000, 5, false, 0, false, {TEAM_GUN})