-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
--[[--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------]]
TEAM_CITIZEN = DarkRP.createJob("Гражданин", {
    color = Color(20, 150, 20, 255),
    model = {
        "models/player/Group01/Female_01.mdl",
        "models/player/Group01/Female_02.mdl",
        "models/player/Group01/Female_03.mdl",
        "models/player/Group01/Female_04.mdl",
        "models/player/Group01/Female_06.mdl",
        "models/player/group01/male_01.mdl",
        "models/player/Group01/Male_02.mdl",
        "models/player/Group01/male_03.mdl",
        "models/player/Group01/Male_04.mdl",
        "models/player/Group01/Male_05.mdl",
        "models/player/Group01/Male_06.mdl",
        "models/player/Group01/Male_07.mdl",
        "models/player/Group01/Male_08.mdl",
        "models/player/Group01/Male_09.mdl"
    },
    description = [[Гражданин является основным слоем общества, чуть ли не бродягой. У данной профессии нет особой роли в жизни города.]],
    command = "citizen",
    max = 0,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    category = "Citizens",
   -- allowedWeapons = {"blunt","pistols"},
})




EAM_CITIZENKID = DarkRP.createJob("Ребенок", {
    color = Color(0, 131, 113, 255),
    model = {
        "models/player/Group01/Female_01.mdl",
        "models/player/Group01/Female_02.mdl",
        "models/player/Group01/Female_03.mdl",
        "models/player/Group01/Female_04.mdl",
        "models/player/Group01/Female_06.mdl",
        "models/player/group01/male_01.mdl",
        "models/player/Group01/Male_02.mdl",
        "models/player/Group01/male_03.mdl",
        "models/player/Group01/Male_04.mdl",
        "models/player/Group01/Male_05.mdl",
        "models/player/Group01/Male_06.mdl",
        "models/player/Group01/Male_07.mdl",
        "models/player/Group01/Male_08.mdl",
        "models/player/Group01/Male_09.mdl"
    },
    description = [[Маленький гражданин.]],
    command = "citizenkid",
    weapons = {"weapon_vape_medicinal", "weapon_bugbait"},
    max = 0,
    PlayerSpawn = function(ply)
        local scale = 0.7
        ply:SetModelScale( scale, 0 )
        ply:SetViewOffset( Vector(0, 0, 64) * scale )
        ply:SetViewOffsetDucked( Vector(0, 0, 28) * scale )
    end,
    salary = 10,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
})



TEAM_ARMIA = DarkRP.createJob("Генерал", {
    color = Color(19, 111, 5, 255),
    model = {
        "models/player/dod_german.mdl"
    },
    description = [[Генерал - главный военнослужащий. \n Отдаёт приказы рядовым, находится в подчинении у мэра ]],
    command = "adrmeds",
    max = 1,
    weapons = {"ptp_cs_ak47", "ptp_cs_deagle", "csgo_bayonet"},
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(150)
    end,
    salary = 700,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = true,
    category = "Citizens",
})

TEAM_ARMIAS = DarkRP.createJob("Рядовой", {
    color = Color(19, 111, 5, 255),
    model = {
        "models/player/dod_american.mdl"
    },
    description = [[Рядовой - военнослужащий. \n Подчиняется приказам генерала.]],
    command = "adrme",
    max = 15,
    weapons = {"ptp_cs_galil", "ptp_cs_deagle", "csgo_bayonet"},
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(150)
    end,
    salary = 650,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = true,
    category = "Citizens",
})

TEAM_ARMIASMED = DarkRP.createJob("Военный Медик", {
    color = Color(19, 111, 5, 255),
    model = {
        "models/player/dod_american.mdl"
    },
    description = [[Восстанавливайте больных бойцов. Лечите ранения.]],
    command = "adrmedic",
    max = 6,
    weapons = {"ptp_cs_galil", "ptp_cs_deagle", "csgo_bayonet", "weapon_medkit"},
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(150)
    end,
    salary = 650,
    admin = 0,
    vote = false,
    hasLicense = true,
    candemote = true,
    category = "Citizens",
})

TEAM_SECKTA = DarkRP.createJob("Священник", {
    color = Color(111, 54, 5, 255),
    model = {
        "models/player/monk.mdl"
    },
    description = [[Священник - представитель духовенства, одной из ступеней христианской церковной иерархии]],
    command = "adept",
    weapons = {"weapon_svechenik"},
    max = 4,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
    end,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
})

TEAM_DETECTIVE = DarkRP.createJob("Детектив", {
    color = Color(0, 85, 151, 255),
    model = {
        "models/player/group01/male_01.mdl",
        "models/player/Group01/Male_02.mdl",
        "models/player/Group01/male_03.mdl",
        "models/player/Group01/Male_04.mdl",
        "models/player/Group01/Male_05.mdl",
        "models/player/Group01/Male_06.mdl",
        "models/player/Group01/Male_07.mdl",
        "models/player/Group01/Male_08.mdl",
        "models/player/Group01/Male_09.mdl"
    },
    description = [[Детектив. Расследуйте убийства, вступайте в различные преступные организации, ловите преступников.]],
    command = "detective",
    weapons = {"ultimate_disguise_kit", "lockpick", "keypad_cracker", "arrest_stick", "unarrest_stick", "weapon_cuff_police", "weapon_357"},
    max = 6,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
    end,
    salary = 600,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Civil Protection",
})

TEAM_BARMEN = DarkRP.createJob("Бармен", { 
    color = Color(106, 144, 148, 255), 
    model = {"models/player/group01/male_04.mdl"}, 
    description = [[Бармен. Откройте бар, продавайте пиво,сигары и многое другое.]], 
    command = "bar", 
    max = 6, 
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
    end,
    salary = 500, 
    admin = 0, 
    vote = false, 
    hasLicense = false, 
    candemote = true, 
    allowedWeapons = {"blunt","pistols"},
})

TEAM_PARKOUR = DarkRP.createJob("Паркурист", { 
    color = Color(0, 255, 255, 255), 
    model = {"models/player/p2_chell.mdl"}, 
    description = [[Паркурист. Вы с самого детсва занимались побегушками во дворе и по сей день вы продолжаете этим заниматся.]], 
    weapons = {"climb_swep2", "realistic_hook"}, 
    command = "parkour", 
    max = 6, 
    PlayerLoadout = function(ply)
            ply:SetHealth(100)
            ply:SetRunSpeed(300) -- скорость бега
    end,
    salary = 500, 
    admin = 0, 
    vote = false, 
    hasLicense = false, 
    candemote = true, 
    category = "Citizens", 
  --  allowedWeapons = {"blunt","pistols"},
})

TEAM_BLACKSS = DarkRP.createJob("Иссохший", {
    color = Color(84, 71, 37, 255),
    model = {"models/player/charple.mdl"},
    description = [[Иссохший. Вы главный враг Человека паука.]],
    weapons = {"weapon_spiderfists", "weapon_cuff_police"},
    command = "blackv",
    max = 1,
    salary = 0,
    PlayerLoadout = function(ply)
        ply:SetHealth(200) -- ХП
        ply:SetMaxHealth(200)
        ply:SetRunSpeed(430) -- скорость бега
        ply:SetJumpPower(750) -- Прыжок
        ply:StripWeapon( "weapon_fists", "weapon_cuff_police" )
    end,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
  --  allowedWeapons = {"allowAll"},
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_MOB = DarkRP.createJob("Наемный Убийца", { 
    color = Color(0, 31, 25, 255), 
    model = {"models/player/group03/male_08.mdl"}, 
    description = [[Вы проработали на многих работах и не одна вам не подошла. Единственное легкое и простое дело для вас - убийство.]], 
    weapons = {"csgo_bayonet", "lockpick", "keypad_cracker"}, 
    command = "mob", 
    max = 6, 
    salary = 500, 
    admin = 0, 
    vote = false, 
    hasLicense = false, 
    candemote = true, 
    category = "Citizens", 
   -- allowedWeapons = {"blunt","pistols", "smgs", "rifles", "snipers", "shotguns"},
})

TEAM_MOBIK = DarkRP.createJob("Опытный наёмник", { 
    color = Color(0, 31, 25, 255), 
    model = {"models/player/group03/male_08.mdl"}, 
    description = [[Вы проработали на многих работах и не одна вам не подошла. Единственное легкое и простое дело для вас - убийство.]], 
    weapons = {"csgo_bayonet", "lockpick", "keypad_cracker", "ptp_cs_awp", "realistic_hook", "ultimate_disguise_kit"}, 
    command = "mobik", 
    max = 6, 
    salary = 500, 
    admin = 0, 
    vote = false, 
    hasLicense = false, 
    candemote = true, 
    category = "Citizens", 
  --  allowedWeapons = {"blunt","pistols", "smgs", "rifles", "snipers", "shotguns"},
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_NASILNIK = DarkRP.createJob("Борец", {
    color = Color(222, 0, 214, 255),
    model = {
        "models/player/Group02/male_08.mdl",
    },
    description = [[Борец насильник, отрабатывайте свои приемы на проходимцах]],
    weapons = {"weapon_rape"},
    command = "nasil",
    max = 4,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
  --  allowedWeapons = {"blunt","pistols"},
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_MANUAK = DarkRP.createJob("Маньяк", {
    color = Color(0, 0, 0, 255),
    model = {
        "models/player/Group02/male_02.mdl",--"models/player/Group02/male_02.mdl",
    },
    description = [[Маньяк. Психически ненормальный человек, готов убить любого за сущий пустяк!]],
    weapons = {"csgo_bayonet", "weapon_crowbar", "ultimate_disguise_kit", "rchainsaw", "weapon_cuff_rope"},
    command = "maniak",
    max = 2,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
  --  allowedWeapons = {"blunt", "allowAll"},
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_BANK = DarkRP.createJob("Банкир", {
    color = Color(0, 105, 67, 255),
    model = {
        "models/player/hostage/hostage_02.mdl",
        "models/player/hostage/hostage_03.mdl",
    },
    description = [[Вы банкир. Может держать легально принтеры и требовать за хранение процент]],
    command = "BANK",
    max = 4,
    salary = 800,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
  --  allowedWeapons = {"allowAll"},
})

TEAM_BOMB = DarkRP.createJob("Террорист", {
    color = Color(222, 222, 0, 255),
    model = {"models/player/guerilla.mdl"},
    description = [[Террорист. Вы хорошо разбираетесь в взрывчатке. Используйте этот навык в своих целях.]],
    command = "Terror",
    max = 1,
    weapons = {"ptp_cs_ak47", "weapon_slam"},
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
   -- allowedWeapons = {"blunt","pistols", "smgs", "rifles"},
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_SECYRITY = DarkRP.createJob("Охранник", {
    color = Color(0, 230, 255, 255),
    model = {"models/player/odessa.mdl"},
    description = [[Охранник. Вы простой гражданин, который желает устроится на какое-нибудь предприятие охранником.]],
    weapons = {"stunstick"},
    command = "oxrana",
    max = 4,
    salary = 600,
    admin = 0,
    vote = false,
    hasLicense = false,
  --  allowedWeapons = {"blunt","pistols", "smgs", "shotguns"},
    candemote = true,
    category = "Citizens",
})

TEAM_SECYRITYVIP = DarkRP.createJob("Старый Охранник", {
    color = Color(0, 230, 255, 255),
    model = {"models/player/odessa.mdl"},
    description = [[Охранник. Вы простой гражданин, который желает устроится на какое-нибудь предприятие охранником.]],
    weapons = {"ptp_cs_pumpshotgun", "stunstick"},
    command = "oxranavip",
    max = 4,
    salary = 750,
    admin = 0,
    vote = false,
    hasLicense = false,
  --  allowedWeapons = {"blunt","pistols", "smgs", "shotguns"},
    candemote = true,
    category = "Citizens",
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_POLICE = DarkRP.createJob("Рядовой Полиции", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/riot.mdl"},
    description = [[Полицейский является защитником каждого, кто живет в городе. Вы можете арестовывать людей, нарушающих законы, участвовать в штурмах, либо патрулировать улицы. \n Хотим напомнить, что вы обязательно должны выполнять поручения шефа полиции. \n Если вы пытаетесь задержать преступника, то, помимо огнестрельного оружия, у вас есть полицейская дубинка, которая является отличным инструментом, приводящим нарушителя в чувство. \n Также, у вас есть ручной таран, который поможет выломать дверь, но не стоит забывать, что для этого нужен ордер на обыск.]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker", "ptp_cs_usp", "weapon_cuff_police"},
    command = "cp",
    max = 6,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(100) -- Броня
    end,
    salary = 600,
    admin = 0,
    vote = false,
    hasLicense = true,
    ammo = {
        ["pistol"] = 160,
    },
    category = "Civil Protection",
})

local admins = {
    "WayZer Team",
    "Trusted",
    "admin",
    "moder",
    "+Helper",
    "Helper",
    "Patron",
}


TEAM_ADMIN = DarkRP.createJob("Администратор", {
    color = Color(131, 53, 233, 255),
    model = {"models/player/barney.mdl"}, -- models/player/barney.mdl
    description = [[NONRP]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "weapon_keypadchecker", "weaponchecker"},
    command = "admin",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = true,
    PlayerSpawn = function(ply)
        if table.HasValue(admins, ply:GetUserGroup()) then
            ply:SetModel("models/wayzer/admin1337.mdl")
        elseif ply:SteamID() == "STEAM_0:0:88099997" then
            ply:SetModel("models/wayzer/admin_boss.mdl")
        end
    end,
    category = "Civil Protection",
    customCheck = function(ply) return CLIENT or ply:GetUserGroup() == "Patron" or ply:GetUserGroup() == "Helper" or ply:GetUserGroup() == "moder"  or ply:GetUserGroup() == "+Eventer" or ply:GetUserGroup() == "Eventer" or ply:GetUserGroup() == "+Eventer" or ply:GetUserGroup() == "admin" or ply:GetUserGroup() == "superadmin" or ply:GetUserGroup() == "+Helper" or ply:GetUserGroup() == "DAdmin" or ply:GetUserGroup() == "DModerator" or ply:GetUserGroup() == "Curator" or ply:GetUserGroup() == "Sponsor" or ply:GetUserGroup() == "DSAdmin" or ply:GetUserGroup() == "Trusted" or ply:GetUserGroup() == "+Helper" or ply:GetUserGroup() == "WayZer Team" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_GANG = DarkRP.createJob("Мафия", {
    color = Color(75, 75, 75, 255),
    model = {
        "models/player/Group03/Female_01.mdl",
        "models/player/Group03/Female_02.mdl",
        "models/player/Group03/Female_03.mdl",
        "models/player/Group03/Female_04.mdl",
        "models/player/Group03/Female_06.mdl",
        "models/player/group03/male_01.mdl",
        "models/player/Group03/Male_02.mdl",
        "models/player/Group03/male_03.mdl",
        "models/player/Group03/Male_04.mdl",
        "models/player/Group03/Male_05.mdl",
        "models/player/Group03/Male_06.mdl",
        "models/player/Group03/Male_07.mdl",
        "models/player/Group03/Male_08.mdl",
        "models/player/Group03/Male_09.mdl"},
    description = [[Мафия - криминальная профессия. Совершайте грабежи в переулках, торгуйте наркотиками, печатайте деньги на денежных принтерах.]],
    weapons = {"unarrest_stick", "weapon_cuff_rope"},
    command = "gangster",
    max = 12,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Gangsters",
})


TEAM_BANDITVIP = DarkRP.createJob("Бандит", {
    color = Color(75, 75, 75, 255),
    model = {
        "models/player/Group03/Female_01.mdl",
        "models/player/Group03/Female_02.mdl",
        "models/player/Group03/Female_03.mdl",
        "models/player/Group03/Female_04.mdl",
        "models/player/Group03/Female_06.mdl",
        "models/player/group03/male_01.mdl",
        "models/player/Group03/Male_02.mdl",
        "models/player/Group03/male_03.mdl",
        "models/player/Group03/Male_04.mdl",
        "models/player/Group03/Male_05.mdl",
        "models/player/Group03/Male_06.mdl",
        "models/player/Group03/Male_07.mdl",
        "models/player/Group03/Male_08.mdl",
        "models/player/Group03/Male_09.mdl"},
    description = [[Бандит - что-то типо VIP мафии, на старте имеет пушки.]],
    weapons = {"unarrest_stick", "ptp_cs_ak47", "pickpocket", "csgo_bayonet", "weapon_cuff_rope"},
    command = "gangstervip",
    max = 4,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    PlayerLoadout = function(ply)
        ply:SetArmor(115)
    end,
    category = "Gangsters",
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_GANGMED = DarkRP.createJob("Лекарь Мафии", {
    color = Color(31, 31, 31, 255),
    model = {
        "models/player/Group03/Female_01.mdl",
        "models/player/Group03/Female_02.mdl",
        "models/player/Group03/Female_03.mdl",
        "models/player/Group03/Female_04.mdl",
        "models/player/Group03/Female_06.mdl",},
    description = [[Доктор Мафии - ваша задача лечить участников вашей мафии]],
    weapons = {"unarrest_stick", "weapon_medkit", "weapon_cuff_rope"},
    command = "gangstermedic",
    max = 3,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Gangsters",
})

TEAM_BANTANK = DarkRP.createJob("Громила", {
    color = Color(75, 75, 75, 255),
    model = {"models/player/phoenix.mdl",}, -- models/player/phoenix.mdl
    description = [[Вы не такой как остальные мафиози, это видно по вашему телосложению. Вы намного крепче и выносливее.]],
    weapons = {"unarrest_stick", "weapon_cuff_rope"},
    command = "bantank",
    max = 1,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Gangsters",
    PlayerLoadout = function(ply)
        ply:SetHealth(200) -- ХП
        ply:SetMaxHealth(200)
        ply:SetArmor(500) -- Броня
    end,
    PlayerSpawn = function(ply)
        local scale = 1.2
        ply:SetModelScale( scale, 0 )
        ply:SetViewOffset( Vector(0, 0, 64) * scale )
        ply:SetViewOffsetDucked( Vector(0, 0, 28) * scale )
    end,
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_VOR = DarkRP.createJob("Вор", {
    color = Color(75, 75, 75, 255),
    model = {"models/player/arctic.mdl"},
    description = [[Вы вор. У вас есть отмычка с помощью которой вы сможете взламывать дверные замки.]],
    weapons = {"lockpick", "keypad_cracker", "pickpocket"},
    command = "vor",
    max = 6,
    salary = 500,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
    end,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Gangsters",
  --  allowedWeapons = {"blunt","pistols", "smgs"},
})

TEAM_HACKER = DarkRP.createJob("Хакер", {
    color = Color(205, 205, 205, 255),
    model = {"models/player/leet.mdl"},
    description = [[Хакер. Вы профессиональный взломщик электроники. Благодаря вашему телефону вас будет трудно вычислить!]],
    weapons = {"lockpick", "keypad_cracker", "unarrest_stick", "krede_wd_phone"},
    command = "hacker",
    max = 3,
    salary = 500,
    admin = 0,
    vote = false,
    hasLicense = true,
    category = "Gangsters",
  --  allowedWeapons = {"blunt","pistols", "smgs"},
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})


TEAM_PROVOR = DarkRP.createJob("Профессиональный Вор", {
    color = Color(75, 75, 75, 255),
    model = {"models/player/arctic.mdl"},
    description = [[Чем отличается проф.вор от простого? Профессиональный вор проверен временем и за годы воровства изучил навык паркура.]],
    weapons = {"lockpick", "keypad_cracker", "climb_swep2", "unarrest_stick", "pickpocket"},
    command = "provor",
    max = 6,
    salary = 500,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
    end,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Gangsters",
   -- allowedWeapons = {"blunt","pistols", "smgs"},
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_GUN = DarkRP.createJob("Продавец оружия", {
    color = Color(255, 140, 0, 255),
    model = "models/player/group01/male_08.mdl",
    description = [[Обустройте магазин и занимайтесь продажей оружия, но для начала приобретите лицензию!]],
    command = "gundealer",
    max = 1,
    salary = 650,
  --  allowedWeapons = {"blunt","pistols", "smgs", "shotguns"},
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
    end,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Citizens",
})

TEAM_VRACH = DarkRP.createJob("Доктор", {
    color = Color(47, 79, 79, 255),
    model = {
        "models/player/group03m/male_01.mdl",
        "models/player/group03m/male_02.mdl",
        "models/player/group03m/male_03.mdl",
        "models/player/group03m/male_04.mdl",
        "models/player/group03m/male_06.mdl",
        "models/player/group03m/male_08.mdl",
        "models/player/group03m/female_02.mdl",
        "models/player/group03m/female_03.mdl"},
    description = [[Доктор. Его задача лечить больных. Он может делать это платно или же бесплатно.]],
    weapons = {"med_kit"},
    command = "vrach",
    max = 6,
    salary = 600,
    admin = 0,
    vote = false,
    hasLicense = false,
   -- allowedWeapons = {"blunt","pistols"},
    medic = true,
    category = "Citizens",
})

TEAM_MEDIC = DarkRP.createJob("Нарколог", {
    color = Color(47, 79, 79, 255),
    model = "models/player/magnusson.mdl",
    description = [[Вы доктор который лечит людей от различных зависимостей. Вы можете незаконно заниматся продажей вредных веществ.]],
    weapons = {"med_kit"},
    command = "medic",
    max = 6,
    salary = 600,
    admin = 0,
    vote = false,
    hasLicense = false,
    medic = true,
    category = "Citizens",
  --  allowedWeapons = {"allowAll"},
})

TEAM_CHIEF = DarkRP.createJob("Капитан полиции", {
    color = Color(20, 20, 255, 255),
    model = {"models/player/urban.mdl"},
    description = [[Капитан Полиции - глава всей полиции в городе. \n Отдавайте приказы своим подчинённым и держите город под защитой]],
    weapons = {"arrest_stick", "unarrest_stick", "ptp_cs_deagle", "ptp_cs_m4", "stunstick", "door_ram", "weaponchecker", "weapon_cuff_police"},
    command = "chief",
    max = 1,
    salary = 830,
    admin = 0,
    vote = false,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(100) -- Броня
    end,
    hasLicense = true,
    chief = true,
    ammo = {
        ["pistol"] = 60,
        ["smg"] = 160,
    },
    category = "Civil Protection",
})

TEAM_POLICES = DarkRP.createJob("Сержант Полиции", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/swat.mdl"},
    description = [[Сержант Полиции. Очередной ранг в полиции. Командуйте рядовыми.]],
    weapons = {"arrest_stick", "unarrest_stick", "ptp_cs_p228", "ptp_cs_famas", "stunstick", "door_ram", "weaponchecker", "weapon_cuff_police"},
    command = "cp2",
    max = 5,
    salary = 900,
    admin = 0,
    vote = false,
    hasLicense = true,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(100) -- Броня
    end,
    chief = true,
    ammo = {
        ["pistol"] = 160,
        ["smg"] = 160,
    },
    category = "Civil Protection",
})

TEAM_SNIPER = DarkRP.createJob("Снайпер Полиции", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/swat.mdl"},
    description = [[Вы зоркий боец. Именно вы должны наблюдать за городом с высоты птичьего полета!]],
    weapons = {"arrest_stick", "realistic_hook", "unarrest_stick", "ptp_cs_p228", "ptp_cs_g3sg1", "stunstick", "door_ram", "weaponchecker", "weapon_cuff_police", "ls_sniper"},
    command = "sniper2",
    max = 4,
    salary = 750,
    admin = 0,
    vote = false,
    hasLicense = true,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(100) -- Броня
    end,
    chief = true,
    ammo = {
        ["pistol"] = 160,
        ["smg"] = 160,
    },
    category = "Civil Protection",
})

TEAM_MOLOT = DarkRP.createJob("Отряд Молот", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/combine_soldier_prisonguard.mdl"},
    description = [[Отряд Молот - особый отряд для проведения спец.операций.]],
    weapons = {"realistic_hook", "arrest_stick", "unarrest_stick", "ptp_cs_fiveseven", "ptp_cs_aug", "stunstick", "door_ram", "weaponchecker", "weapon_cuff_police", "swat_shield"},
    command = "molot",
    max = 6,
    salary = 750,
    admin = 0,
    vote = false,
    hasLicense = true,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(100) -- Броня
    end,
    ammo = {
        ["pistol"] = 160,
        ["smg"] = 160,
    },
    category = "Civil Protection",
})

TEAM_TANKIST = DarkRP.createJob("Джаггернаут", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/combine_super_soldier.mdl"},
    description = [[Вы особый боец. На вашем теле мощная броня. Бадитам это не понравится!]],
    weapons = {"arrest_stick", "unarrest_stick", "stunstick", "door_ram", "weaponchecker", "ptp_cs_para", "weapon_cuff_police"},
    command = "tank",
    max = 1,
    salary = 800,
    admin = 0,
    vote = false,
    hasLicense = true,
    ammo = {
        ["smg"] = 560,
    },
    PlayerLoadout = function(ply)
        ply:SetHealth(200) -- ХП
        ply:SetMaxHealth(200)
        ply:SetArmor(500) -- Броня
    end,
    PlayerSpawn = function(ply)
        local scale = 1.2
        ply:SetModelScale( scale, 0 )
        ply:SetViewOffset( Vector(0, 0, 64) * scale )
        ply:SetViewOffsetDucked( Vector(0, 0, 28) * scale )
    end,
    category = "Civil Protection",
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_POLICEMED = DarkRP.createJob("Полицейский Медик", {
    color = Color(25, 25, 170, 255),
    model = {"models/player/gasmask.mdl"},
    description = [[Полицейский медик занимается лечением своих товарищей.]],
    weapons = {"arrest_stick", "unarrest_stick", "ptp_cs_usp", "ptp_cs_pumpshotgun", "stunstick", "door_ram", "weaponchecker", "med_kit", "weapon_cuff_police"},
    command = "cp3",
    max = 6,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
        ply:SetArmor(100) -- Броня
    end,
    salary = 700,
    admin = 0,
    vote = false,
    hasLicense = true,
    ammo = {
        ["pistol"] = 160,
        ["buckshot"] = 100,
    },
    category = "Civil Protection",
})

TEAM_MAYOR = DarkRP.createJob("Мэр", {
    color = Color(150, 20, 20, 255),
    model = "models/player/breen.mdl", -- models/player/breen.mdl
    description = [[Вы глава города. Устанавливайте законы и контролируйте порядок во всех частях города.]],
    weapons = {"stungun", "stunstick", "arrest_stick", "unarrest_stick", "weaponchecker", "weapon_cuff_police"},
    command = "mayor",
    max = 1,
    salary = 1125,
    admin = 0,
    vote = true,
    hasLicense = false,
    mayor = true,
   -- allowedWeapons = {"blunt","pistols"},
    category = "Civil Protection",
    PlayerDeath = function(ply)
                if ply:Team() == TEAM_MAYOR then
                        ply:changeTeam( TEAM_CITIZEN, true )
                        for k,v in pairs( player.GetAll() ) do
                                DarkRP.notify(v, 1, 4, "Мэр был убит!")
                        end
                end
        end,
})

TEAM_NALOG = DarkRP.createJob("Налоговый инспектор", {
    color = Color(38, 71, 87, 255),
    model = {"models/player/hostage/hostage_01.mdl", "models/player/hostage/hostage_04.mdl"},
    description = [[Собирайте налоги с жителей города]],
    weapons = {"stungun", "stunstick", "weapon_cuff_police", "weapon_nalog"},
    command = "nalog",
    max = 2,
    salary = 666,
    admin = 0,
    vote = false,
    hasLicense = false,
    category = "Citizens",
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_HOBO = DarkRP.createJob("Бомж", {
    color = Color(80, 45, 0, 255),
    model = "models/player/corpse1.mdl",
    description = [[Вы бомж. Постройте шалаш и попрошайничайте деньги у прохожих]],
    weapons = {"weapon_bugbait"},
    command = "hobo",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
  --  allowedWeapons = {"blunt"},
    hobo = true,
    category = "Citizens",
})

TEAM_AFHOBO = DarkRP.createJob("Авторитетный Бомж", {
    color = Color(80, 45, 0, 255),
    model = "models/player/corpse1.mdl",
    description = [[Авторитетный Бомж. Вы прославились своей профессиональной игрой на гитаре. Все бомжи в городе вас уважают.]],
    weapons = {"weapon_bugbait", "guitar_stalker", "csgo_bayonet"},
    command = "afhobo",
    max = 1,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
-- allowedWeapons = {"blunt"},
    hobo = true,
    category = "Citizens",
})

TEAM_METH = DarkRP.createJob("Варщик мета", {
    color = Color(0, 80, 60, 255),
    model = {
        "models/player/group02/male_06.mdl",
    },
    description = [[Мет моя жизнь, блять!]],
    command = "creatormeth",
    max = 6,
    PlayerLoadout = function(ply)
        ply:SetHealth(100) -- ХП
    end,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = true,
    category = "Citizens",
})

TEAM_VAC = DarkRP.createJob("Работник Valve", {
    color = Color(205, 255, 0, 255),
    model = "models/player/gman_high.mdl",
    description = [[Выдай VAC какому-нибудь чуваку и скорее свали от него, пока он тебя не отпи....]],
    weapons = {"vacban"},
    command = "vacjob",
    max = 2,
    salary = 700,
    admin = 0,
    vote = false,
  --  allowedWeapons = {"blunt","pistols", "smgs"},
    hasLicense = false,
    candemote = true,
    category = "Citizens",
    customCheck = function(ply) return CLIENT or ply:GetUserGroup()  ~= "user" end,
    CustomCheckFailMsg = "Эта работа только для VIP пользователей"
})

TEAM_BANNED = DarkRP.createJob("Птица", {
    color = Color(0, 0, 0, 255),
    model = "models/crow.mdl",
    description = [[You are banned]],
    command = "iambanned",
    max = 0,
    salary = 0,
    admin = 0,
    vote = false,
    hasLicense = false,
    candemote = false,
    hobo = true,
    category = "Other",
    PlayerLoadout = function( ply )
        return true
    end,
    PlayerSpawn = function(ply)
        ply:SetModel(bird[math.random(1,2)])
        ply:SetViewOffset( Vector(0, 0, 64) * 0.2 )
        ply:SetViewOffsetDucked( Vector(0, 0, 28) * 0.2 )
        ply:SetMoveType(MOVETYPE_FLY)
        
    end,
    customCheck = function(ply)
        return false, "Зачем тебе это?"
    end
})



TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1
TEAM_COOK    = TEAM_COOK     or -1

-- Door groups
AddDoorGroup("Полицейский участок", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR, TEAM_POLICEMED, TEAM_POLICES, TEAM_TANKIST, TEAM_MOLOT, TEAM_SNIPER, TEAM_KAPMOLOT, TEAM_DETECTIVE, TEAM_SUPERPOLICE)
AddDoorGroup("Мэрия", TEAM_MAYOR, TEAM_CHIEF, TEAM_POLICE, TEAM_POLICEMED, TEAM_POLICES, TEAM_TANKIST, TEAM_MOLOT, TEAM_SNIPER, TEAM_KAPMOLOT, TEAM_DETECTIVE, TEAM_SUPERPOLICE, TEAM_NALOG)
AddDoorGroup("Военная База", TEAM_ARMIA, TEAM_ARMIAS)

-- Agendas

-- Group chats
DarkRP.createGroupChat(function(ply) return ply:isCP() end)
DarkRP.createGroupChat(TEAM_MOB, TEAM_GANG)
DarkRP.createGroupChat(function(listener, ply) return not ply or ply:Team() == listener:Team() end)

-- Initial team when first spawning
GAMEMODE.DefaultTeam = TEAM_CITIZEN

-- Teams that belong to Civil Protection
GAMEMODE.CivilProtection = {
    [TEAM_POLICE] = true,
    [TEAM_CHIEF] = true,
    [TEAM_MAYOR] = true,
    [TEAM_MOLOT] = true,
    [TEAM_POLICES] = true,
    [TEAM_POLICEMED] = true,
    [TEAM_TANKIST] = true,
    [TEAM_SNIPER] = true,
    [TEAM_DETECTIVE] = true,
}

-- Hitman team

-- Demote groups
DarkRP.createDemoteGroup("Citizens", {TEAM_AFHOBO, TEAM_HOBO, TEAM_MAYOR, TEAM_POLICEMED, TEAM_TANKIST, TEAM_MOLOT, TEAM_POLICES, TEAM_CHIEF, TEAM_MEDIC, TEAM_VRACH, TEAM_GUN, TEAM_PROVOR, TEAM_VOR, TEAM_BANTANK, TEAM_GANG, TEAM_POLICE, TEAM_SECYRITY, TEAM_BOMB, TEAM_BANK, TEAM_MANUAK, TEAM_NASILNIK, TEAM_HACKER, TEAM_MOB, TEAM_SPIDERMAN, TEAM_PARKOUR, TEAM_TVMASTER, TEAM_DETECTIVE})

-- Default categories
DarkRP.createCategory{
    name = "Citizens",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 100,
}

DarkRP.createCategory{
    name = "Civil Protection",
    categorises = "jobs",
    startExpanded = true,
    color = Color(25, 25, 170, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 101,
}

DarkRP.createCategory{
    name = "Gangsters",
    categorises = "jobs",
    startExpanded = true,
    color = Color(75, 75, 75, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 101,
}

DarkRP.createCategory{
    name = "Other",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 107, 0, 255),
    canSee = fp{fn.Id, true},
    sortOrder = 255,
}
