-- 17.04
IGS.LVL.Add(1)
	:SetName("Новичок")
	:SetBonus(function(pl)
		local bonus = pl:IGSFunds() * .2
		pl:AddIGSFunds(bonus,"Бонус за первое пополнение")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил " .. PL_IGS(bonus) .. " в качестве бонуса за первое пополнение счета")
	end)
	:SetDescription("При первом пополнении счета вы получите 20 процентов к сумме пополнения")

IGS.LVL.Add(100)
	:SetName("Стартанувший")
	:SetBonus(function(pl)
		local bonus = pl:IGSFunds() * .10
		pl:AddIGSFunds(bonus, "Стартанувший")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил " .. PL_IGS(bonus) .. " за уровень *Стартанувший*")
	end)
	:SetDescription("Бонус 10% от суммы баланса на донат счету")

IGS.LVL.Add(500)
	:SetName("В теме")
	:SetBonus(function(pl)
		local bonus = pl:IGSFunds() * .15
		pl:AddIGSFunds(bonus, "В теме")
		pl:addMoney(1000000)
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил 1.000.000$ в качестве бонуса за уровень *В теме*")
	end)
	:SetDescription("Ты уже точно шаришь! За твое пожертвование тебе 15% к пополнению и миллиончик!")

IGS.LVL.Add(1000)
    :SetName("Бывалый")
	:SetBonus(function(pl)
		pl:AddIGSFunds(100,"Бывалый")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил 100 руб  за получение донат уровня *Бывалый*")
	end)
	:SetDescription("Бонус 100 рублей на баланс, вне зависимости от суммы пополнения! Просто добей этот уровень!")

IGS.LVL.Add(1500)
	:SetName("Вроде не бомж")
	:SetBonus(function(pl)
		local bonus = pl:IGSFunds() * .15
		pl:AddIGSFunds(bonus, "Вроде не бомж")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил " .. PL_IGS(bonus) .. " за уровень *Вроде не бомж*")
	end)
	:SetDescription("Бонус 15% от суммы баланса на донат счету")

IGS.LVL.Add(2000)
	:SetName("Точно не бомж")
	:SetBonus(function(pl)
		pl:AddIGSFunds(200,"Бывалый")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил 200 руб за получение донат уровня *Точно не бомж*")
	end)
	:SetDescription("Точно не бомж! Награда: 200 рублей на баланс сверху!")

IGS.LVL.Add(2500)
	:SetName("При деньгах")
	:SetBonus(function(pl)
		local bonus = pl:IGSFunds() * .25
		pl:AddIGSFunds(bonus, "При деньгах")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил " .. PL_IGS(bonus) .. " за уровень *При деньгах*")
	end)
	:SetDescription("Бонус 25% от суммы баланса на донат счету ")

IGS.LVL.Add(3000)
	:SetName("Щедрый")
	:SetBonus(function(pl)
		local bonus = pl:IGSFunds() * .30
		pl:AddIGSFunds(bonus, "Щедрый")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил " .. PL_IGS(bonus) .. " за уровень *Щедрый*")
	end)
	:SetDescription("Бонус 30% от суммы баланса на донат счету ")

IGS.LVL.Add(4000)
	:SetName("Очень щедрый")
	:SetBonus(function(pl)
		local bonus = pl:IGSFunds() * .35
		pl:AddIGSFunds(bonus, "Очень щедрый")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил " .. PL_IGS(bonus) .. " за уровень *Очень щедрый*")
	end)
	:SetDescription("Бонус 35% от суммы баланса на донат счету")

IGS.LVL.Add(5000)
	:SetName("Пиздец щедрый")
	:SetBonus(function(pl)
		pl:AddIGSFunds(10,"Получение донат уровня под профессией")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил донат уровень *Пиздец щедрый* и отображение уровней над своей головой")
	end)
	:SetDescription("Получишь отображение уровней над головой")
	

IGS.LVL.Add(6000)
    :SetName("Мажор")
	:SetBonus(function(pl)
		pl:AddIGSFunds(450,"Бонус за достижение уровня")
		pl:addMoney(1000000)
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил 450 руб и 1.000.000$ за получение донат уровня *Мажор*")
	end)
	:SetDescription("Уровень мажор, 1.000.000$ и 450 руб")

IGS.LVL.Add(7000)
	:SetName("Супермажик")

IGS.LVL.Add(8000)
	:SetName("Гипермажик")

IGS.LVL.Add(9000)
	:SetName("Убермажор")

IGS.LVL.Add(10000)
	:SetName("Миллионер")
	:SetBonus(function(pl)
		pl:AddIGSFunds(500,"Бонус за достижение уровня")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил Rainbow Physgun и 500 руб за получение донат уровня *Миллионер*")
	end)
	:SetDescription("Уровень Миллионер, разноцветный физган и 500 рублей!")

IGS.LVL.Add(12000)
	:SetName("МультиМиллионер")

IGS.LVL.Add(15000)
	:SetName("Миллиардер")
	:SetBonus(function(pl)
		pl:AddIGSFunds(600,"Бонус за достижение уровня")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил Rainbow Wear и 600 руб за получение донат уровня *Миллиардер*")
	end)
	:SetDescription("Уровень Миллиардер, разноцветная одежда и 500 рублей!")

IGS.LVL.Add(20000)
	:SetName("МультиМиллиардер")
	:SetBonus(function(pl)
		pl:AddIGSFunds(10,"Получение радужного уровня под профессией")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил донат уровень *МультиМиллиардер* и радужные уровни над своей головой")
	end)
	:SetDescription("Получишь радужное отображение уровней над головой")

IGS.LVL.Add(25000)
	:SetName("Нахуй с дороги")
	:SetDescription("Получишь переливающийся Crazy Physgun с суперяркими цветами")
	:SetBonus(function(pl)
		pl:AddIGSFunds(10,"Получение крейзи физгана")
		IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил Crazy Physgun за достижение донат уровня *НАХУЙ С ДОРОГИ*")
	end)

IGS.LVL.Add(30000)
	:SetName("Сядь в лужу, я пройду")

IGS.LVL.Add(35000)
	:SetName("Я тебя куплю")

IGS.LVL.Add(40000)
	:SetName("Я куплю тебя и твою семью")

IGS.LVL.Add(50000)
    :SetName("Бог один и это Я")
	:SetBonus(function(pl)
	    pl:AddIGSFunds(2500,"Бонус за достижение уровня")
	   	IGS.NotifyAll(pl:getDarkRPVar('rpname').." получил самый последний донат уровень! Я В ШОКЕ!11")
		IGS.Notify(pl,"Я сомневаюсь что кто-то сюда доберется, но если ты добрался до этого уровня. Напиши мне в вк vk.com/ocherkala")
	end)
	:SetDescription("Это самый последний уровень с невероятным бонусом")
